### ISSUE TITLE
Multiple Nodes and more

### ISSUE THREAD

**Issue by A380Coding** [csuermann/node-red-contrib-presence-faker#36]
I have multiple nodes configured with Inputmessage delivering the sunset time as windowBegin. All nodes show nextCycle at exactly sunset. Do they now all start at sunset? Is the first triggerpoint not random?
They all have random on/off times right?

Is it possible to get the next triggertime as an output. Under the note it says next Cycle, can I get this as a message to show it on the UI?

As others mentioned a minimum off time in between the random cycles would be a nice option even though it is kind of ambiguous to other settings.

**Comment by csuermann** [comment]
The schedule would start for all presence-faker nodes simultaneously but their on/off blocks would be randomized. Of course, if you set "first block = ON", all your nodes would emit their ON messages at the same time, so you might want to leave that setting as "first block = OFF".

It is not (yet) possible to get the next trigger time as an output message. As a workaround you could use a "Status" node to scrape it.

I am considering to introduce min & max OFF duration instead of the "ON times" setting. What do you think of that?

**Comment by A380Coding** [comment]
I tried, but it shows me "next cycle: xxx" with the same time regardless of "first block = on" or "first block = off".
I could add a random offset to the sunset time as input.

Thanks, status node does the trick :)

I like the way it is now very much actually.
I thought an option for setting min off time would be nice. Dependent on the other options "on times" and "on time min duration" it can be calculated what the max value for min off time would be.
Say "on times" = 2, "min duration" = 1h and the time frame is from 21:00 - 24:00.
That is 2*1h= 2h on time duration in total. We have 3h time frame from 21:00 to 24:00 which equals 1h off time. for each "on time" 1h/2=0,5h as max value for min off time. Even so 0,5h would not allow any random on/off times any more and make it static.

Or maybe just allowing an off time setting between 0 and 10 minutes in order to avoid a 1 minute off duration between random on blocks. The purpose is to avoid minimal off times. If it is then not fitting with the other settings, the last block could be truncated if required.

For the "min On Times" it is the same issue. If I set it to 900 for the given time frame with a "ON min duration" of 12h it is also not possible to do that. Not sure if there is a check that would block such a setting.

So after all, the input values typed in need to be realistic, but some guidance/warning if they do not make sense would be helpful.

**Comment by csuermann** [comment]
> I tried, but it shows me "next cycle: xxx" with the same time regardless of "first block = on" or "first block = off".

Yes, that is to be expected because the window of all presence-faker nodes are set to the exact same start time (sunset). But once the cycle start time has been reached, you would see all your nodes emit their configured payloads. Here it does make a difference whether you set the "first block" option to ON or OFF, since with ON all your (for example) lights would simultaneously get switched on at the moment of sunset, whereas they would come on in a more staggered / randomized fashion if you chose "first block = OFF".

**Comment by A380Coding** [comment]
Ok thanks!
